package cybermatrix;

public class Repository {
	
	public static final String qs[] = {
			"1. I am also referred to as TERRA. What\'s my shape?",
			"2. I am an American actress. I started my career in 1999 in television series Get Real. In 2008, I was nominated for Academy Award for Best Actress for my lead role in Rachel Getting Married. Which year was my 1st movie as a lead actress released in?",
			"3. I directed India's first short film \"The flower of Persia\" in 1898. What was the name of my film company?",
			"4. I am an Indian Playback Singer and I won recognition through a televised singing contest, Meri Awaz Suno. I have done a song in collaboration with the international pop star Enrique Iglesias in his album Euphoria. Which song is it?",
			"5. I am the annual literary fest of the 1st private sector medical college in India started in 1953. Which year was I started in?",
			"6. Who is the all-time best-selling fiction writer in the world, whose 78 crime novels have sold an estimated 2 billion copies?",
			"7. We are the founders of the enterprise which bought the publishing company of famous duo Charles and Gerald on October 1, 1971. Who are we?",
			"8. I have written a famous novel in 1954, whose title is the English translation of the Hebrew word \"Beelzebub\". Who am I?",
			"9. To what type of animal was Robert Burns referring in his poem that starts \"Wee, sleekit, cowrin, tim'rous beastie...\"?",
			"10. I am an English poet and playwright. I am often called England's 'national poet' and the \"Bard of Avon\". In which of my plays does the line \"A horse! A horse! My kingdom for a horse\" appear?",
			
			"11. I was a Jewish victim of the Holocaust. During my stay in Amsterdam to hide from the Nazis, I used an autograph book as a diary which later became famous worldwide and was translated into many languages. Into how many languages has my diary been translated?",
			"12. In 2008, this renowned artist played his banjo during a brain surgery. Who was he?",
			"13. I am a U.S. music superstar. I missed a penalty kick during the opening ceremony festivities at the World Cup soccer finals in 1994. Who am I?",
			"14. I am the CEO of a luxury Fashion and Style house. It manufactured uniforms for The Schutzstaffel (SS) during the 1930's. Who am I?",
			"15. In which author's novels would you find the character of Admiral Sir Miles Messervy?",
			"16. I am the director of the short film \"I Killed My Lesbian Wife, Hung Her on a Meat Hook, and Now I Have a Three-Picture Deal at Disney\". I won an Academy Award and a Golden Globe Award for the screenplay for 'Good Will Hunting'. Who was my co-writer in it?",
			"17. In 1944, I was the last case of a woman being tried and convicted in the U.K. for witchcraft. Where was I born?",
			"18. In an electronic variant of the mechanical Rubik's Cube, sliding a finger across its faces causes its patterns of colored lights to rotate the same way they would on a mechanical cube. Where in New York was it introduced in 2009?",
			"19. Identify the movie in which these dialogues were quoted. \"That's two priests driving a Ferrari. When's the last time you saw two priests drive a Ferrari?",
			"20. Pingali, a writer and a geophysicist, designed a flag to bring the whole nation together in the year _______ which was disapproved of it as he said that in red color Hindu community finds representation and in green Muslim, but all the other communities of India are not represented in this flag.",
			
			"21. I am an Italian physicist, mathematician, astronomer, and philosopher. I played a major role in the Scientific Revolution. Name the two universities I studied in.",
			"22. I was the second Indian to get my doctorate in English literature from Cambridge University. I used to introduce myself as Mitti ka tan, masti ka man, kshan-bhar jivan - mera parichay. On which famous personality did I write my last poem?",
			"23. I am the grandson of the Mughal Emperor Zaheeruddin Muhammad Babur, the ruler who founded the Mughal dynasty in India. I did not go to Persia with my parents but was raised by my uncle in the eastern parts of the Safavid Empire. What was his name?",
			"24. He was a renowned 'Classical Sanskrit' writer, widely regarded as the greatest poet and dramatist in the Sanskrit language. He composed the famous poem Meghduta. How many plays did he write?",
			"25. From Which University Did The Person Who Said \"I Possess The DNA Of Leonard Nimoy\" In The Famous T.V. Series Do His M.A?",
			"26. Coca Cola Joined Hands With Which Cooperation To Launch The \"Support My School\" Campaign, A Movement For Healthy, Active And Happy Schools?",
			"27. What Prize Did The Maker Of Transistors Get At The National Academy Of Sciences?",
			"28. I am a large rodent, about the size of a small housecat, and I like to eat flowers and plants. I double my body weight during the summer to fatten up for the winter. I am a true hibernator; I sleep through the long, cold winters. I love to eat and then lie on a rock in the sun. Some say I have a yellow belly. Who am I?",
			"29. I am a member of the rabbit family and I live in a rocky habitat. My ears are short and round, but large for the size of my head. My tail is invisible. You often hear my shrill alarm, \"Enk! Enk!\" before you see me. I remain active throughout the year and spend the summer gathering vegetation and drying it out in \"haystacks\" to store under rocks for food during winter. Who am I?",
			"30. I am the largest member of the deer family, standing at 6-7 feet at the shoulder. My huge antlers are flat and resemble paddles. I prefer to browse on buds, twigs, bark, and leafy vegetation. I often am seen in or near water where I submerge to find food or get rid of pesky insects. I can run 35 mph. who am I?",
			
			"31. I was put under a spell by the Goddess Hera and killed my three sons and wife by mistake while under the vex; and was later ordered to perform ten tasks to ease my guilt. Who am I?",
			"32. I am an offspring of the Titan Kronus, and the Lord of the Underworld; jealous of my own brother, I tried to overthrow him and take over his territory many times. Who am I?",
			"33. I am the brother of Chryasor, born when Perseus killed my mother Medusa; I helped carry Zeus' thunderbolts for him and I also helped the hero Bellaophone to defeat the Chimera. Who am I?",
			"34. I was cursed by Athena for sacrilizing her temple and was turned into a monster so hideous that men froze automatically as they look upon my face. Who am I?",
			"35. I am an off-spring of Zeus, cast away by my grandfather as a baby; but later slayed the Gorgon Medusa and married the princess Andromeda. Who am I?",
			"36. Identify the picture (HINT: Best known for his mime abilities.)",
			"37. Three brothers, Alan, Brian and Chuck are all different ages. They each do strange things with numbers, that is, instead of saying the actual number, they change it in a certain way first. One brother divides the number in half. Another brother squares the number. The third brother reverses the digits. (21 becomes 12, 50 and also 5 become 5). When they were asked their ages, the oldest whispered his \"age\" to the thinnest, who whispered it to Chuck, who whispered it to the youngest, who answered: 27. Then the youngest whispered his \"age\" to the tallest, who whispered it to Brian, who whispered it to the shortest, who answered: 23. Lastly, the youngest whispered his \"age\" to the shortest, who whispered it to the thinnest, who whispered it to Alan, who answered: 16. What is Alan's age?",
			"38. A record was set in the 2005-06 EPL season, when a player scored a Premiership hat-trick against Manchester United for the first time. What was the final tally of goals of his team at the end of the match?",
			"39. How many of the following have the same number of carbon rings? Triphenylene, pyrene, tetracene, benzo[a]pyrene",
			"40. The famous Italian writer Dante was born in which region of Italy?",
			
			"41. In 1991, Otogawa was the priest at which personality's wedding?",
			"42. The writer of \"hell hath no fury\" is",
			"43. Who was the original owner of the resurrection stone?",
			"44. What does the number 12 associate with as per the weasley's clock?",
			"45. Who hid the diadem in the forest of Albania?",
			"46. A fictional character, I am a detective in the NYPD and am engaged to Jenny O'mally. I work under Detective Kate Beckett. Who am I?",
			"47. The author who stated \"If I tried to write 'Midnight Sun' now, in my current frame of mind, James would probably win and all the Cullens would die\"?, has five siblings. One of them is a leading character in her books. Name him.",
			"48. A bestseller writer, he died on 30th January 2007, from pneumonia. Who was he?",
			"49. When Superman comes to Earth, he lands in a small fictional town of______ in kansas?",
			"50. The characters daffy duck, tweety, and the Tasmanian devil are characters of the ___________ (2 words)",
			
			"51. Characters dressed in purple, orange, white and green are characters of which popular cartoon show?",
			"52. What is this art form or design known as?",
			"53. In B.R.Chopra's Mahabharat, Mukesh Khanna was initially selected for the role of which character but was later re-cast as Bheeshma?",
			"54. There is a kind of cheese which is made backwards. It is also a name of a city. How many football world cups this country where the city is has won?",
			"55. Which extraordinary tourist spot is located in the Ladakh valley between Dras and Sururivers?",
			"56. During the Slave dynasty or the Mamluk dynasty in Indian History, name the king who was once a mere slave ?",
			"57. This 2-word term for ambitious men had its origins in the group that replaced Ottoman sultan Abdul Hamid in 1909",
			"58. The Georgia O'Keeffe Museum, home to the largest permanent collection of her works, is in this state capital",
			"59. Usual adjective referring to the size of 8 1/2 X 14\" paper",
			"60. The name of this earth-friendly polishing cleanser is French for \"good friend\"",
			
			"61. This is the cover of a popular Pink Floyd album. Find the track 4 of the album.",
			"62. I started my club career with Notts County, got transferred to Arsenal, then Liverpool, and now I currently play for Stoke City. Who was my manager at 'Anfield'?",
			"63. I am the first Indian to take a hat-trick in One-Day Internationals. Who was my Second victim in the process?",
			"64. If you were around in the late '60s and '70s, you might have listened to tunes played on an eight-track tape. How many reels of tape does an eight-track cartridge have?",
			"65. Which city is also known as the Big Apple?",
			"66. Longer but narrower than a king-sized bed is this state's \"king\"",
			"67. In which country was the drama 'Dream High' filmed and produced? (Hint: Two words)",
			"68. 1. The Last Airbender\n 2. Honey 2",
			"69. Bluetooth is a wireless technology, but the term originally referred to a king who erected two runic stones. What are these stones called?",
			"70. What is my character's name in the popular TV show Family Guy?",
			
			"71. Berkshire Hathaway",
			"72. What is the next 3 letters in this riddle? e t t f f s s _ _ _",
			"73. I am an Indian American entrepreneur who co-founded the Hotmail email service. Which free messaging service did I start?",
			"74. Who was the first U.S. president who assumed informal version of his first name while at office, he openly discussed his battle with hemorrhoids. He was also the recipient of the Nobel Peace Prize.",
			"75. An American singer-songwriter, musician, multi-instrumentalist, performer, producer, actress, and political activist. has garnered nine Grammy Awards from the National Academy of Recording Arts and Sciences. She sang the title song for which Bond film?",
			"76. I was born in 1945 and am a retired AFL sportsman who regularly appears in the media. I court controversy, have been sued for defamation and in 1997 my 25 year old girlfriend hit me with a car.",
			"77. As part of my work with the royal mint I was involved in the conviction of 28 coin Counterfeiters. I would often dress up as a commoner and frequent bars and taverns in order to gather evidence. I wrote a number of religious papers dealing with the literal interpretation of the Bible. I was a member of the Parliament of England but legend has it that the only time I spoke was to comment on a cold draught and request that a window be closed. I lectured in optics and in 1675 published my first hypothesis. Who am I?",
			"78. Born in 1890, I was born in Devon, England the youngest of three children in a conservative, well-to-do family. I wrote over 66 novels in my career. One of my most enduring characters who went on to become one of the very famous fictitious detectives",
			"79. I am the only person to be inducted into the Rock and Roll Hall of Fame three separate times. I play guitar and sing. In 1998, I founded a center for recovering alcohol and drug addicts in Antigua. Who am I?",
			"80. Announced in December 2011, by Greg Kroah-Hartman this project aims to put some Android drivers, patches and features back into the Linux kernel, starting in Linux 3.3.,further integration being expected for Linux Kernel 3.4. What is it?",
			
			"81. In ancient Olympic victory ceremonies, after the herald would announce the name of the Olympic winner, his father's name, and his homeland in a loud voice,__________________ would place the sacred olive tree wreath, or kotinos, on the winner's head.",
			"82. What is the name of the system set up by Bank of Scotland for customers of the Nottingham Building Society (NBS) in 1983 that allows on-line viewing of statements, bank transfers and bill payments at home?",
			"83. A substance made of pure carbon fetched the Nobel Prize in Physics for 2010 to a Russian-born British-Dutch physicist working at the University of Manchester; but the theory of this substance was  first explored by €˜_________'  in 1947 as a starting point for understanding the electronic properties of more complex,3D graphite.",
			"84. The person is a philanthropist, inventor and co - founder of one of the biggest cooperation of world. The person is among the top 50 richest persons of world. Added to this the figure is owner of 2 professional sports team of NFL & NBA .identify figure",
			"85. Born in West Germany, was a world no.1 professional tennis player from the US with 7 Grand Slams to his credit. Became more famous for his very popular catchphrase directed towards an umpire during a match in Wimbledon in 1981.",
			"86. The country known for its natural beauty, where the World Wide Web was invented. Uses its Latin name on its stamps",
			"87. An American professional golfer who has played on the PGA Tour and now plays mostly on the Champions Tour. He had played 87 straight Grand Slam tournaments until a shoulder injury forced him to miss the 1996 British Open. He ended nine years of final-round frustration by winning the 1996 Memorial Tournament. Who is he?",
			"88. It is a television series about three women who work for a private investigation agency, and is one of the first shows to showcase women in roles traditionally reserved for men. The series is broadcast in the USA on the ABC Television Network from 1976 to 1981 and is one of the most successful series of the 1970s.Name the series.",
			"89. What tournament did Arnold Palmer say he would play in as long as he could walk and the only Grand Slam event Lee Trevino never won?",
			"90. What woman won five U.S. figure skating titles from 1969 to 1973, but never an Olympic gold medal?",
			
			"91. This Mathematician is known for deriving one of the most basic and widely used theorem of mathematics. He was the first to notice that the morning star and evening star were one and the same, in 530 B.C",
			"92. A French fashion designer and founder of a very famous fashion brand she was the only designer on Time's Most Important People of the Century. She was born on the 19th of August in France. Who is she?",
			"93. It is a medical drama series which airs on CBS from 1969 to 1976. The show stars James Daly as Dr. Paul Lochner and Chad Everett (Richard Bradford in the pilot) as Dr. Joe Gannon, surgeons working in an otherwise unnamed university hospital in Los Angeles. The show focuses both on the lives of the doctors as well as the patients showcased each week. What is the name of the show?",
			"94. He was one of the Founding Fathers of the United States and the first US ambassador to France. As a scientist he never put patents on any of his inventions, he believed that everyone should have access to them. He invented a much improved version of the Glass Harmonica.",
			"95. Many considered me one of the most prolific authors of the 20th century. I wrote numerous fictional romantic novels and also won a place in the Guinness Book of World Records for writing 26 books in the year 1983.Who am I?",
			"96. Who is the Director of the Disney movie has a married couple called Roger and Anita Radcliffe?",
			"97. This actor was 1st seen in the TV show Ed in the episode a thousand cranes, name his 2 upcoming movies.",
			"98. Felt around Christmas, Shift in oceanic temperature n atmospheric conditions in tropical pacific that disrupts weather around the world .which phenomena is being talked?",
			"99. X is an American; former businessman, stockbroker, investment advisor, and financier. He is the former non-executive chairman of the NASDAQ stock market, and the admitted operator of a Ponzi scheme that is considered to be the largest financial fraud in U.S. history. Identify X.",
			"100. X has triggered the rise of a new field of electronics called Spintronics which has been used extensively in the read heads of modern hard drives and magnetic sensors. A high X is preferred for optimal data storage density. Research continues to enable disk drive densities exceeding 1 Terabyte per square inch. Identify X.",
			
			"101. A Co- founder of Texas Instruments, an American engineer and businessman. He was co-chair of the committee that merged the IRE and the American Institute of Electrical Engineers (AIEE) into the present Institute of Electrical and Electronics Engineers (IEEE)",
			"102. Company that is the world's largest manufacturer of vertical transportation." },
			
			

			ansr[] = { 	"oblate spheroid",	
		"2001",							
		"royal bioscope",	
		"heartbeat",	
		"2002", 
		"agatha christie",	
		"jack palmer and doug weld",	
		"william golding",	
		"mouse",		
		"richard iii", 
		"55", 
		"virginian eddie adcock", 
		"diana ross", 
		"claus-dietrich lahrs", 
		"sir ian fleming",
		"matt damon", 
		"callander", 
		"american international toy fair", 
		"cannonball run", 
		"1916", 
		"university of pisa, university of padua",
		"indira gandhi", 
		"mirza askari", 
		"three",
		"university of san diego", 
		"ndtv",
		"comstock prize in physics", 
		"", 
		"pika", 
		"moose", 
		"zeus",
		"hades", 
		"pegasus", 
		"medusa", 
		"perseus", 
		"charlie chaplin",
		"twenty one", 
		"four", 
		"three", 
		"tuscany", 
		"steve jobs",
		"david weber", 
		"cadmus peverell", 
		"mortal peril",
		"rowena rawenclaw", 
		"seamus dever", 
		"jacob",
		"sidney sheldon", 
		"smallville", 
		"looney tunes",
		"scooby doo", 
		"pookalam", 
		"drona", 
		"zero", 
		"baily bridge",
		"iltutmish", 
		"young turks", 
		"santafe", 
		"legal", 
		"bon ami",
		"sheep", 
		"rafael benitez", 
		"ian smith", 
		"one", 
		"new york",
		"california", 
		"south korea", 
		"seychelle gabriel",
		"jelling stones", 
		"meg griffin", 
		"warren buffett", 
		"e n t",
		"jaxtrsms", 
		"jimmy carter", 
		"sheryl crow", 
		"sam newman",
		"isaac newton", 
		"agatha christie", 
		"eric clapton",
		"android mainlining project", 
		"hellanodikis", 
		"homelink",
		"philip wallace", 
		"paul allen", 
		"john mcenroe",
		"switzerland", 
		"tom watson", 
		"charlie's angels",
		"the masters", 
		"janet lynn", 
		"pythagoras", 
		"coco chanel",
		"medical center", 
		"benjamin franklin", 
		"barbara cartland",
		"stephen herek", 
		"rise of the guardian, star trek 2",
		"el nino",
		"bernard madoff", 
		"magnetic tunnelling effect",
		"patrick eugene haggerty", 
		"otis" };

	public static final String ans28[] = { "yellow bellied marmot", 
		"lophuromys luteogaster", 
		"yellow-bellied brush-furred rat" };
}
